-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 21:33:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BankApplication
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BankApplication
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BankApplication` DEFAULT CHARACTER SET utf8 ;
USE `BankApplication` ;

-- -----------------------------------------------------
-- Table `BankApplication`.`UserInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BankApplication`.`UserInfo` (
  `UserID` INT NOT NULL,
  `LoginPassword` VARCHAR(45) NULL,
  `SecretQuestion` VARCHAR(45) NULL,
  `TransactionPassword` VARCHAR(45) NULL,
  `LockStatus` INT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankApplication`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BankApplication`.`Customer` (
  `AccountID` INT NOT NULL AUTO_INCREMENT,
  `CustomerName` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Pancard` VARCHAR(45) NULL,
  `UserID` INT NULL,
  PRIMARY KEY (`AccountID`),
  INDEX `UserID_idx` (`UserID` ASC),
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `BankApplication`.`UserInfo` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankApplication`.`AccountMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BankApplication`.`AccountMaster` (
  `AccountID` INT NOT NULL,
  `AccountType` VARCHAR(45) NULL,
  `AccountBalance` INT NULL,
  `OpenDate` VARCHAR(45) NULL,
  INDEX `AccountID_idx` (`AccountID` ASC),
  CONSTRAINT `AccountID`
    FOREIGN KEY (`AccountID`)
    REFERENCES `BankApplication`.`Customer` (`AccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankApplication`.`PayeeDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BankApplication`.`PayeeDetails` (
  `AccountID` INT NULL,
  `PayeeAccountID` INT NOT NULL,
  `PayeeName` VARCHAR(45) NULL,
  PRIMARY KEY (`PayeeAccountID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankApplication`.`FundTransfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BankApplication`.`FundTransfer` (
  `AccountID` INT NULL,
  `FundtransferID` INT NOT NULL,
  `PayeeAccountID` INT NULL,
  `DateOfTransfer` VARCHAR(45) NULL,
  `TransferAmount` INT NULL,
  PRIMARY KEY (`FundtransferID`),
  INDEX `PayeeAccountID_idx` (`PayeeAccountID` ASC),
  INDEX `AccountID_idx` (`AccountID` ASC),
  CONSTRAINT `PayeeAccountID`
    FOREIGN KEY (`PayeeAccountID`)
    REFERENCES `BankApplication`.`PayeeDetails` (`PayeeAccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FundTransfer_AccountID`
    FOREIGN KEY (`AccountID`)
    REFERENCES `BankApplication`.`Customer` (`AccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankApplication`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BankApplication`.`Transaction` (
  `AccountID` INT NULL,
  `TransactionID` INT NOT NULL,
  `TransactionDesc` VARCHAR(45) NULL,
  `DateOfTransaction` VARCHAR(45) NULL,
  `TransAmount` INT NULL,

  PRIMARY KEY (`TransactionID`),
  INDEX `AccountID_idx` (`AccountID` ASC),
  CONSTRAINT `Transaction_AccountID`
    FOREIGN KEY (`AccountID`)
    REFERENCES `BankApplication`.`Customer` (`AccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankApplication`.`ServiceTracker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BankApplication`.`ServiceTracker` (
  `AccountID` INT NULL,
  `ServiceID` INT NOT NULL,
  `ServiceDesc` VARCHAR(45) NULL,
  `ServiceRaisedDate` VARCHAR(45) NULL,
  `ServiceStatus` VARCHAR(45) NULL,
  PRIMARY KEY (`ServiceID`),
  INDEX `AccountID_idx` (`AccountID` ASC),
  CONSTRAINT `ServiceTracker_AccountID`
    FOREIGN KEY (`AccountID`)
    REFERENCES `BankApplication`.`Customer` (`AccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
